name: Daily GitHub Top Repos Update

on:
  schedule:
    # 每天UTC时间20:00运行（中国时间次日早晨4点，UTC+8）
    - cron: '0 20 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-top-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 使用个人访问令牌来允许后续提交更改
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run GitHub Top Repos Script
      env:
        GitHubToken: ${{ secrets.GITHUBTOKEN }}  # 使用您设置的Repository secret
      run: |
        # python script/generate.py
        echo "Running StoreData4RestAPI_GraphQL.py..."
        python script/StoreData4RestAPI_GraphQL.py
        echo "Running AnalyzeData2.py.."
        python script/AnalyzeData2.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: GitHub top repos $(date -u +'%Y%m%d')"
        git push
